[package]
name = "dvh"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
serde = ["dep:serde"]